use_frameworks!

target 'SelectCountry_Example' do
  pod 'SelectCountry', :path => '../'

  target 'SelectCountry_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
